export class UIData {
  lineSpacing: number = 2
  resolution: any = {
    width: 180
  }
  textPositions: any = {
    center: {
      alignX: 'center',
      alignY: 'center',
      offsetPixelsX: 0,
      offsetPixelsY: 0,
      offsetPercentX: 0,
      offsetPercentY: 0,
    },
    centerTop: {
      alignX: 'center',
      alignY: 'top',
      offsetPixelsX: 0,
      offsetPixelsY: 0,
      offsetPercentX: 0,
      offsetPercentY: 25,
    }
  }
  font: any = {
    ' ': [
      [false],
      [false],
      [false],
      [false],
      [false],
    ],
    '.': [
      [false],
      [false],
      [false],
      [false],
      [true],
    ],
    ',': [
      [false],
      [false],
      [false],
      [false],
      [true],
      [true],
    ],
    A: [
      [true, true, true],
      [true, false, true],
      [true, true, true],
      [true, false, true],
      [true, false, true]
    ],
    B: [
      [true, true, true, false],
      [true, false, true, false],
      [true, true, true, true],
      [true, false, false, true],
      [true, true, true, true],
    ],
    C: [
      [true, true, true],
      [true, false, false],
      [true, false, false],
      [true, false, false],
      [true, true, true],
    ],
    D: [
      [true, true, false],
      [true, false, true],
      [true, false, true],
      [true, false, true],
      [true, true, false],
    ],
    E: [
      [true, true, true],
      [true, false, false],
      [true, true, false],
      [true, false, false],
      [true, true, true],
    ],
    F: [
      [true, true, true],
      [true, false, false],
      [true, true, true],
      [true, false, false],
      [true, false, false],
    ],
    G: [
      [true, true, true, true],
      [true, false, false, false],
      [true, false, true, true],
      [true, false, false, true],
      [true, true, true, true],
    ],
    H: [
      [true, false, true],
      [true, false, true],
      [true, true, true],
      [true, false, true],
      [true, false, true],
    ],
    I: [
      [true],
      [true],
      [true],
      [true],
      [true],
    ],
    J: [
      [true, true, true],
      [false, false, true],
      [false, false, true],
      [true, false, true],
      [true, true, true],
    ],
    K: [
      [true, false, true],
      [true, false, true],
      [true, true, false],
      [true, false, true],
      [true, false, true],
    ],
    L: [
      [true, false, false],
      [true, false, false],
      [true, false, false],
      [true, false, false],
      [true, true, true],
    ],
    M: [
      [true, false, false, false, true],
      [true, true, false, true, true],
      [true, false, true, false, true],
      [true, false, false, false, true],
      [true, false, false, false, true],
    ],
    N: [
      [true, false, false, true],
      [true, true, false, true],
      [true, false, true, true],
      [true, false, false, true],
      [true, false, false, true],
    ],
    O: [
      [true, true, true],
      [true, false, true],
      [true, false, true],
      [true, false, true],
      [true, true, true],
    ],
    P: [
      [true, true, true],
      [true, false, true],
      [true, true, true],
      [true, false, false],
      [true, false, false],
    ],
    Q: [
      [true, true, true, false],
      [true, false, true, false],
      [true, false, true, false],
      [true, false, true, false],
      [true, true, true, true],
    ],
    R: [
      [true, true, true],
      [true, false, true],
      [true, true, false],
      [true, false, true],
      [true, false, true],
    ],
    S: [
      [true, true, true],
      [true, false, false],
      [true, true, true],
      [false, false, true],
      [true, true, true],
    ],
    T: [
      [true, true, true],
      [false, true, false],
      [false, true, false],
      [false, true, false],
      [false, true, false],
    ],
    U: [
      [true, false, true],
      [true, false, true],
      [true, false, true],
      [true, false, true],
      [true, true, true],
    ],
    V: [
      [true, false, true],
      [true, false, true],
      [true, false, true],
      [true, true, true],
      [false, true, false],
    ],
    W: [
      [true, false, false, false, true],
      [true, false, false, false, true],
      [true, false, true, false, true],
      [true, true, false, true, true],
      [true, false, false, false, true],
    ],
    X: [
      [true, false, true],
      [true, false, true],
      [false, true, false],
      [true, false, true],
      [true, false, true],
    ],
    Y: [
      [true, false, true],
      [true, false, true],
      [true, true, true],
      [false, true, false],
      [false, true, false],
    ],
    Z: [
      [true, true, true],
      [false, false, true],
      [false, true, false],
      [true, false, false],
      [true, true, true],
    ],
  }
}